import Header from "./Components/Header/Header"
import Footer from "./Components/Footer/Footer"
import Hero from "./Components/HeroSection/Hero"
import Logo from "./assets/MyAssets/envicify-solution.png"
import Logo1 from "./assets/MyAssets/envicify-solution 1.png"
import Button from "./Components/Button/Button"
import Hero_image from "../src/assets/MyAssets/hero-picture.png"
import About from "./Components/About/About"
import Service from "./Components/Services/Service"
import BackgroundVideo from "./assets/MyAssets/background.mp4"
import AboutImage from "./assets/MyAssets/aboutimage.png"
// export { ThemeContext, ContentProvider, useTheme } from "./Components/ContextAPI/Mode"
export { Header, Footer, Hero, Logo, Button, Hero_image, About, Service, BackgroundVideo, Logo1,AboutImage }